- pallets/amm/src/lib.rs
- pallets/amm/src/mock.rs
- pallets/amm/src/tests.rs
- pallets/asset-registry/src/lib.rs
- pallets/asset-registry/src/tests.rs
- pallets/exchange/src/direct.rs
- pallets/exchange/src/lib.rs
- pallets/exchange/src/mock.rs
- pallets/exchange/src/tests.rs
- primitives/src/lib.rs
- primitives/src/traits.rs
- runtime/src/lib.rs
Changes in this PR:
- Exchange algorithm update
- Exchange pallet refactor
- Added trading limits
- other various little fixes and improvements
> Hydra update

- pallets/amm/src/benchmarking.rs
AMM benchmarks update to reflect recent changes in amm sell functionality. 
Also updated the amounts in sell benchmark to use more realistic values.
> AMM: benchmarks update

- pallets/exchange/src/direct.rs
While resolving intentions - move directly from reserved balance instead of two steps ( unreserve -> transfer )/
> Exchange: transfer from reserved

- pallets/amm/src/lib.rs
- pallets/amm/src/mock.rs
- pallets/amm/src/tests.rs
- pallets/exchange/benchmarking/src/mock.rs
- pallets/exchange/src/direct.rs
- pallets/exchange/src/lib.rs
- pallets/exchange/src/mock.rs
- pallets/transaction-multi-payment/benchmarking/src/mock.rs
- pallets/transaction-multi-payment/src/mock.rs
- primitives/src/lib.rs
- primitives/src/traits.rs
- runtime/src/lib.rs
Latest updates to exchange pallet and primitives.
Fees handling reworked as previously implemented in hydra-dx repo.
Use of spot price calc from math package.
> Latest improvements (exchange, fees,spot price)

- Cargo.lock
- node/Cargo.toml
- pallets/transaction-multi-payment/Cargo.toml
- runtime/Cargo.toml
Issue introduced when new payment pallet was introduced. 
Only present when building node for benchmarking.
> Fix benchmark build

- node/src/chain_spec.rs
- pallets/faucet/Cargo.toml
- pallets/faucet/src/lib.rs
- pallets/faucet/src/mock.rs
- pallets/faucet/src/tests.rs
- runtime/src/lib.rs
Also added tests. Rampage mode should be set to on only when on testnet as everybody will be able to mint any asset with this. (old behavior)
> Added config to faucet (max limit, mintable assets and rampage mode)

- pallets/exchange/README.md
Readme update. Includes desc of the pallet, intentions and order-matching algorithm
> Exchange Readme

- Cargo.lock
Math package update to include last minor fix
> Math deps update 

- .maintain/bench-check/bench_check.py
- README.md
- scripts/check_performance.sh
Updated readme to include prerequisites for the performance check.
updated the script to check precise python version.
> Bench check update

- Cargo.lock
- runtime/Cargo.toml
Fixed building node with runtime-benchmark features which were introduced with the staking changes.
> Benchmark build fix

- Cargo.lock
- pallets/amm/Cargo.toml
use of specific revision for hydra-dx-math package to avoid potential  build issues due to upcoming breaking changes in the math package
> hydradx-math crate tied to revision

- pallets/claims/src/lib.rs
- pallets/claims/src/migration.rs
- pallets/claims/src/traits.rs
> fix: claims migration based on pallet version

- pallets/claims/src/benchmarking.rs
- pallets/claims/src/lib.rs
- pallets/claims/src/tests.rs
Fixed claims pallet build with runtime benchmarks features.
> fix: claims benchmarking build fix

- node/src/chain_spec.rs
- runtime/src/constants.rs
The value of DOLLARS has been divided by 10 (and the number of decimal places reduced by 1).
Fixes: #109
> refactor: update decimals of DOLLARS

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
Added pallet-scheduler - module for scheduling dispatches
#158
> feat: add pallet scheduler

- scripts/check_performance.sh
Minor update to check performance script to use bench wizard as library module.
Using benchwizard as executable command required the benchwizard  to be present in PATH. And observing various user's problems, some of them did not   have the tool automatically added to the path after  installation.
on bench machine
> fix: update perf check script

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
Adjust parameters for staking:
Ideal staking rate = 16%
Max inflation rate / I(npos) = 8%
Fixes: #171
> feat!: set reward curve params for inc. testnet

- node/src/chain_spec.rs
- runtime/src/constants.rs
- runtime/src/lib.rs
Setup a technical committee
Fixes: #149
> feat!: setup technical committee

- scripts/check_performance.sh
Remove python3.8 explicit handling
#178
> bug(perf-check): fix bench-wizard install/upgrade

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/constants.rs
- runtime/src/lib.rs
> feat!: change epoch to 4 hours 

- runtime/src/lib.rs
Update tx fee multiplier for pallet transaction payment.
> fix(runtime): add tx fee multiplier

- pallets/genesis-history/src/lib.rs
> refactor(genesis-history): derived default genesis chain

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/lib.rs
> fix!: add election fallback on-chain

- runtime/src/constants.rs
- runtime/src/lib.rs
Adds unit tests for time units
Fixes #204
> feat: add tests for time units

- .github/workflows/tests.yml
> ci: Build workflow from fork PR

- Cargo.lock
- pallets/amm/Cargo.toml
- pallets/amm/src/benchmarking.rs
- pallets/amm/src/lib.rs
- pallets/amm/src/tests.rs
- pallets/amm/src/weights.rs
- pallets/exchange/benchmarking/src/lib.rs
- pallets/exchange/src/lib.rs
- pallets/exchange/src/tests.rs
- pallets/exchange/src/weights.rs
- pallets/transaction-multi-payment/benchmarking/src/lib.rs
- pallets/transaction-multi-payment/src/tests.rs
- pallets/transaction-multi-payment/src/weights.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
- runtime/src/lib.rs
> feat: change Price type

- Cargo.lock
- pallets/exchange/benchmarking/src/lib.rs
- pallets/exchange/src/tests.rs
- pallets/transaction-multi-payment/benchmarking/src/lib.rs
- pallets/transaction-multi-payment/src/tests.rs
- pallets/xyk/src/benchmarking.rs
- pallets/xyk/src/lib.rs
- pallets/xyk/src/tests.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
Reverted Price type to substrate's FixedU128.
> refactor: revert price type to fixedu128

- Cargo.lock
- node/Cargo.toml
- pallets/asset-registry/Cargo.toml
- pallets/claims/Cargo.toml
- pallets/exchange/Cargo.toml
- pallets/exchange/benchmarking/Cargo.toml
- pallets/faucet/Cargo.toml
- pallets/transaction-multi-payment/Cargo.toml
- pallets/transaction-multi-payment/benchmarking/Cargo.toml
- pallets/xyk/Cargo.toml
- primitives/Cargo.toml
- primitives/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Add Debug, Copy and Eq trait to fee::Fee struct.
Traits are required by LBP implementation.
> refactor: add traits to Fee struct

- README.md
Add actual types scope for node.
> docs: Update types config Readme

- Cargo.lock
- pallets/xyk/Cargo.toml
Use hydra-dx-math package from crates.io instead of github directly.
> chore(xyk): use math from crates.io

- scripts/check_performance.sh
Update to latest bench-wizard which support db read/write benchmark
> feat: add db benchmark to check perf script

- .github/workflows/tests.yml
- infrastructure/infra.tf
Update AMI image with valid token
> fix: update AMI image with new key

- .github/workflows/tests.yml
- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec/dev.rs
- node/src/chain_spec/local.rs
- node/src/chain_spec/mod.rs
- node/src/chain_spec/staging.rs
- node/src/chain_spec/testnet.rs
- node/src/command.rs
- node/src/service.rs
- node/src/testing_chain_spec.rs
- primitives/Cargo.toml
- primitives/src/constants.rs
- runtime/common/Cargo.toml
- runtime/common/src/lib.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
> chore: upgrade to polkadot-v0.9.16

- scripts/snakenet-migration/index.js
- scripts/snakenet-migration/package.json
- populate module prefixes
- remove democracy locks
- exclude address in validate
> feat: snakenet migration of other modules

- Dockerfile
Issue: https://github.com/galacticcouncil/Basilisk-node/issues/210
> fix: changed base OS in the dockerfile

- Cargo.lock
- node/src/chain_spec/mod.rs
- node/src/testing_chain_spec.rs
- runtime/common/src/lib.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
Added collator-rewards pallet to runtime.
#389
> feat: collator rewards pallet

- node/Cargo.toml
- pallets/claims/Cargo.toml
- primitives/Cargo.toml
- runtime/common/Cargo.toml
- runtime/hydra-dx/Cargo.toml
- runtime/testing-hydra-dx/Cargo.toml
Normalize manifests of cargo package files
Reordered cargo.toml manifest according to importance of metadata
> chore: normalize manifests of cargo package files

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- node/src/chain_spec/mod.rs
- node/src/testing_chain_spec.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
This PR uses the new collator rewards pallet implementation from https://github.com/galacticcouncil/warehouse/pull/57 to implement rewards in a different way:
`CollatorRewards` now provides a `SessionManager` implementation that wraps an inner `SessionManager` to
+ grab the collator set for each session
+ be notified of each session end and pay out the rewards to all non-excluded collators
without changing anything about the session keys.
Addresses [#2hypfvk](https://app.clickup.com/t/2hypfvk)
The original collator rewards implementation required us to change the session key types which would mean a runtime migration as well as changes for how to run the collators.
I ran a manual test with the testing runtime where I observed the events and token changes I would expect if the collators …
> feat!: Use new collator-rewards pallet with SessionManager

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/buy.rs
- pallets/omnipool/src/tests/sell.rs
> fix: omnipool - dont allow sell/buy with same asset in/out

- pallets/omnipool/src/lib.rs
ensure that imbalance after update is always negative. 
Fixes #434
> feat: omnipool - ensure imbalance is negative

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/types.rs
> refactor: omnipool imbalance update

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/refund.rs
> fix: omnipool - dont allow LRNA refund

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/mod.rs
- pallets/omnipool/src/tests/tradability.rs
> fix: omnipool - allow only sell/buy as hub asset tradable state

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/init_pool.rs
- pallets/omnipool/src/tests/mock.rs
> fix: check if stable asset is registered in init pool

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/mock.rs
- pallets/omnipool/src/tests/remove_liquidity.rs
> fix: omnipool - ensure non-zero values

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/add_liquidity.rs
- pallets/omnipool/src/tests/add_token.rs
- pallets/omnipool/src/tests/buy.rs
- pallets/omnipool/src/tests/init_pool.rs
- pallets/omnipool/src/tests/invariants.rs
- pallets/omnipool/src/tests/mock.rs
- pallets/omnipool/src/tests/mod.rs
- pallets/omnipool/src/tests/positions.rs
- pallets/omnipool/src/tests/remove_liquidity.rs
- pallets/omnipool/src/tests/sell.rs
- pallets/omnipool/src/tests/verification/scenario_04.rs
- pallets/omnipool/src/tests/verification/scenario_05.rs
- pallets/omnipool/src/tests/verification/scenario_06.rs
- pallets/omnipool/src/tests/verification/scenario_08.rs
- pallets/omnipool/src/tests/verification/scenario_09.rs
- pallets/omnipool/src/tests/verification/scenario_10.rs
- pallets/omnipool/src/tests/verification/scenario_11.rs
- pallets/omnipool/src/types.rs
delta imbalance is calculated within add/remove state changes calculation.
asset tvl removed
> chore: audit issues 

- .github/workflows/tests.yml
Add step for generating wasm and ci and add them to the artifacts in CI
> feat: add testnet components to build

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
- integration-tests/src/lib.rs
- integration-tests/src/omnipool_init.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
> feat: filter transfers of LRNA to omnipool account

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
Fixes https://github.com/galacticcouncil/warehouse/issues/91
> test: add integration tests for call filter

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/types.rs
This PRs adds some interface that can be used by other pallets that build on top of -  subpools or liquidity mining.
> feat: add omnipool pallet interface

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/oracle.rs
- pallets/circuit-breaker/Cargo.toml
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool/Cargo.toml
- runtime/common/Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
- scraper/Cargo.toml
+ update warehouse to oracle with fixed on_trade price
+ change block number provider from Relay Chain to `System` (parachain blocks)
Spot price (price as ratio of liquidity after trade) can and does differ from the price that is calculated from trade amounts. This PR uses an adjusted version of the oracle pallet that uses liquidity to determine the price.
regression test in the warehouse PR: https://github.com/galacticcouncil/warehouse/pull/188
> fix: adjust Oracle to Parachain Blocks and Liquidity-based Prices

- Cargo.lock
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool-liquidity-mining/src/lib.rs
This PR fixes misleading comments in `omnipool-liquidity-mining` pallet.
* #527 
* #530
> fix: LM misleading comments

- Cargo.lock
- integration-tests/Cargo.toml
- pallets/circuit-breaker/Cargo.toml
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool/Cargo.toml
- runtime/common/Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
This PR updates repo to latest warehouse with fixed math for liquidity mining.
Details of the fix: https://github.com/galacticcouncil/HydraDX-math/pull/98
> fix: liquidity mining math overflow

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/non_native_fee.rs
- integration-tests/src/polkadot_test_net.rs
- pallets/circuit-breaker/Cargo.toml
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/provider.rs
- runtime/common/Cargo.toml
- runtime/common/src/lib.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/xcm.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
- runtime/testing-hydradx/src/xcm.rs
This PR integrates latest change in multi transaction payment pallet which reworks non-native fee payment.
> feat: integrate fee payment rework

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
- integration-tests/src/non_native_fee.rs
- integration-tests/src/omnipool_init.rs
- integration-tests/src/oracle.rs
- integration-tests/src/polkadot_test_net.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
> feat: filter transfers of omnipool assets to omnipool

- .maintain/pallet-weight-template-no-back.hbs
> chore: update weights template

- Cargo.lock
- integration-tests/Cargo.toml
- pallets/circuit-breaker/Cargo.toml
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool/Cargo.toml
- runtime/common/Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
- fix: multicurrency payment fee rounding - https://github.com/galacticcouncil/warehouse/pull/206
- (feat: rework fee payment - https://github.com/galacticcouncil/warehouse/pull/204 just the merge commit, the commit just before the merge was referenced)
> chore: update warehouse to include fee fixes

- pallets/dca/Cargo.toml
- pallets/dca/src/lib.rs
- pallets/dca/src/tests/on_initialize.rs
FIxes and adjustment for DCA pallet coming from testing
> fix: added missing trade failed event to dca

- Cargo.lock
- pallets/asset-registry/Cargo.toml
- pallets/asset-registry/src/lib.rs
- pallets/asset-registry/src/tests.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
> feat: emit `MetadataSet` event register extrinsic

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
> fix: allow uniques calls

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/dca.rs
- integration-tests/src/polkadot_test_net.rs
- pallets/dca/Cargo.toml
- pallets/dca/src/tests/on_initialize.rs
Fix failing integration tests and also fixed them in the sense that we don't need to update them always when benchmark changes
> test: dca integration tests fixed

- Cargo.lock
- pallets/dca/Cargo.toml
- pallets/dca/src/lib.rs
- pallets/dca/src/tests/mock.rs
- pallets/dca/src/tests/on_initialize.rs
- pallets/dca/src/tests/schedule.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
> fix: add dca min trading limit check

- Cargo.lock
- math/Cargo.toml
- math/src/stableswap/tests/invariants.rs
Adjust invariant test to ensure LP does not receive more that provided.
> fix: adjust stableswap invariant test

- primitives/src/lib.rs
- runtime/hydradx/src/xcm.rs
> fix: merge ecosystem-wide xcm conversion

- Cargo.lock
- pallets/referrals/Cargo.toml
- pallets/referrals/src/benchmarking.rs
- pallets/referrals/src/lib.rs
- pallets/referrals/src/tests/claim.rs
This PR changes storage type from STorageMap to CountedStorageMap as we need the count of items in the storage.
> feat: referrals - change storage type

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/referrals.rs
- pallets/referrals/Cargo.toml
- pallets/referrals/src/benchmarking.rs
- pallets/referrals/src/lib.rs
- pallets/referrals/src/tests.rs
- pallets/referrals/src/tests/claim.rs
- pallets/referrals/src/tests/flow.rs
- pallets/referrals/src/tests/trade_fee.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
We need to track trader rewards separately so it does not count towards referral level.
> feat: referrals - track trader rewards separately

- Cargo.lock
- pallets/referrals/Cargo.toml
- pallets/referrals/src/lib.rs
- pallets/referrals/src/tests/trade_fee.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
> fix(referrals): do not store zero shares in TraderShares

- Cargo.lock
- pallets/referrals/Cargo.toml
- pallets/referrals/src/lib.rs
- pallets/referrals/src/tests.rs
- pallets/referrals/src/tests/claim.rs
- pallets/referrals/src/tests/convert.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
> fix(referrals): remove asset from pending conversions on failure

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/README.md
- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/router_execution.rs
- pallets/omnipool/src/traits.rs
Update code docs and readme to be up to date with implementation.
> docs: updated omnipool

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/router.rs
- pallets/route-executor/Cargo.toml
- pallets/route-executor/src/lib.rs
- pallets/route-executor/src/tests/buy.rs
- pallets/route-executor/src/tests/mock.rs
- pallets/route-executor/src/tests/sell.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- scripts/init-testnet/chopsticks/fakeSignature.js
- scripts/init-testnet/package-lock.json
- scripts/init-testnet/package.json
> fix: router Executed event

- Cargo.lock
- Cargo.toml
- integration-tests/Cargo.toml
- integration-tests/src/evm.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/evm/precompiles/mod.rs
- runtime/hydradx/src/lib.rs
> feat: add standard EVM precompiles

- node/res/hydradx.json
> chore: add stake.plus bootnodes

- node/res/hydradx.json
Please consider adding RadiumBlock bootnodes to Hydration
Better p2p connectivity
> chore: add RadiumBlock bootnodes to Hydration

- Cargo.lock
- pallets/liquidation/src/tests/mock.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/evm/aave_trade_executor.rs
- runtime/hydradx/src/evm/precompiles/erc20_mapping.rs
- runtime/hydradx/src/lib.rs
- traits/src/evm.rs
> feat: aave trade executor runtime api

- launch-configs/fork/prepare-state-for-zombienet.js
+ set updatedAt to 0 on all global farms
+ bump ALICE balance to whole supply
> feat: reset farms on fork zombienet

- Cargo.lock
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/governance/mod.rs
- runtime/hydradx/src/governance/old.rs
- runtime/hydradx/src/lib.rs
rebased https://github.com/galacticcouncil/hydration-node/pull/1081 for patch release
> fix: governance six second blocks migration

- .github/workflows/tests.yml
- Cargo.lock
- pallets/dca/Cargo.toml
- pallets/dca/src/lib.rs
Add new regresstion tests for DCA schedules
> test: dca regression tests

- Cargo.lock
- Cargo.toml
- launch-configs/zombienet/local.json
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
fixes https://github.com/galacticcouncil/hydration-node/issues/1046
> feat: add storage reclaim
