galacticcouncil/hydration-node

- runtime/src/lib.rs
This was actually not that bad as i originally expected. 
Extrinsic base weight includes payment swap extra weight which is now taken from the swap currency benchmarked weight.
> Extrinsic base weight update

- scripts/check_performance.sh
Install bench-wizard cli tool as part of the check_performance script. 
#167 
Currently, the script exists and user has to manually install the tool and rerun the script afterwards. This change helps with that ,so no need to exit, install and rerun again.
Manually on benchbot machine.
> chore(perf-check): install bench wizard as part of the check perf script

- runtime/src/constants.rs
We've set wrong DOLLARS constant the transactions are too cheap and the storage for identities is 0.05$ instead of 5$
> fix!:  set DOLLARS constant to correct number

- .github/workflows/tests.yml
- node/Cargo.toml
- node/src/service.rs
As part of my investigation in https://github.com/paritytech/substrate/issues/4678#issuecomment-827709562, I also found that this was wrong (although it doesn't fix the original issue).
> fix(node): configure justification import for full node

- Cargo.lock
- pallets/transaction-multi-payment/Cargo.toml
- pallets/transaction-multi-payment/benchmarking/Cargo.toml
transaction-multi-payment pallet has dependency on local balances pallet implementation. This is only dev dependency used in test.
This PR moves the dependency to dev dependencies section and it changes to use substrate balances instead of local balances.
> fix(multi-payment): move balances dependency to dev-dependency

- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec.rs
- runtime/Cargo.toml
- runtime/src/constants.rs
- runtime/src/lib.rs
Set epoch_config for babe pallet at genesis.
Well, it does not work without it!
> fix!: set babe epoch config at genesis

- Cargo.lock
- Cargo.toml
Libsrock-db was updated. The patch can be now discarded.
> fix(chore): discard patch for libsrock-db

- node/build.rs
- utils/build-script-utils/src/version.rs
In build-script-utils , there is runtime name hardcoded to "hydra-dx-runtime". That means, it is only possible to use it with that given runtime.
This PR is making this value configurable so it is possible to use with different runtimes.
In Basilisk, for example - we don't need to have the same utils but could use the crate from hydradx-node repo.
Nope.
To be able to use it in Basilisk or even with testing runtime ( when support for this is merged ) - it would be great to have a possibility to specify runtime name for which cargo keys should be generated. 
Locally.
> refactor(build-script): allow to specify runtime

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/src/lib.rs
Add support for batch transaction execution.
fixes #218 
Manually in local environment.
> feat: add utility pallet to allow batch txs execution

- pallets/exchange/Cargo.toml
- pallets/exchange/src/direct.rs
- pallets/exchange/src/lib.rs
- pallets/exchange/src/tests.rs
Add intention_id to the IntentionResolvedDirectTradeFees event.
This commit resolves #248.
This change changes the signature of the IntentionResolvedDirectTradeFees event.
I think it does it for good - to be similar to `IntentionResolvedDirectTrade`
The change is pretty straightforward, on each direct match we have access to two intentions and by the `fee: true` flag we already know all of the tranansactions which are taking part in taking the fees. Also those transactions has a field `from`. So, by matching that `from` field with intention data we are computing the intention IDs. 
In my opinion it is a pretty robust way of doing things. Because I didn't touch the matching rules, and also, the change will adopt itself to any further changes in the fees rules.
Fixes: #248 
That missing …
> feat(exchange)!: Update IntentionResolvedDirectTradeFees event

- Cargo.lock
- pallets/exchange/Cargo.toml
- pallets/exchange/benchmarking/Cargo.toml
- pallets/exchange/benchmarking/src/lib.rs
- pallets/exchange/src/tests.rs
- pallets/xyk/Cargo.toml
- pallets/xyk/src/benchmarking.rs
- pallets/xyk/src/lib.rs
- pallets/xyk/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Fee in buy_price calculation is wrongly assigned to the `amount_out`. The correct operation order is to compute `amount_in` first, and then apply fee to this value in the next step.
> fix(amm): buy_price calculation

- Cargo.lock
- pallets/exchange/Cargo.toml
- pallets/exchange/benchmarking/src/lib.rs
- pallets/exchange/src/lib.rs
- pallets/exchange/src/tests.rs
- pallets/xyk/Cargo.toml
- pallets/xyk/src/benchmarking.rs
- pallets/xyk/src/lib.rs
- pallets/xyk/src/tests.rs
- primitives/Cargo.toml
- primitives/src/traits.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
The AMMTransfer struct is extended to contain two new fields: fee_assetID and fee_amount.
The fee amount is subtracted from the amount_in variable in the AMMTransfer struct.
This change is required in LBP pallet because we need a way to access the fee in `execute_buy/sell(transfer: AMMTransfer)` functions and send it to corresponding fee_receiver account.
> feat: add fee to AMMTransfer

- Cargo.lock
- node/src/chain_spec.rs
- pallets/transaction-multi-payment/Cargo.toml
- pallets/transaction-multi-payment/benchmarking/Cargo.toml
- pallets/transaction-multi-payment/benchmarking/src/lib.rs
- pallets/transaction-multi-payment/benchmarking/src/mock.rs
- pallets/transaction-multi-payment/src/lib.rs
- pallets/transaction-multi-payment/src/mock.rs
- pallets/transaction-multi-payment/src/tests.rs
- pallets/transaction-multi-payment/src/traits.rs
- primitives/Cargo.toml
- primitives/src/traits.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Added possibility to set a price for accepted currencies to use in case pool does not exist.
Note that this is breaking change - storage has changed.
https://github.com/galacticcouncil/Basilisk-node/issues/45
This provides possibility to pay tx fee in non-native currency even if pool between selected currencies and native asset does not exist yet.
only tests so far.
> feat!: multi payment fallback price

- pallets/exchange/Cargo.toml
- pallets/exchange/src/lib.rs
- pallets/exchange/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
`AssetBalanceLimitExceeded`  is splitted into two errors, one for sell case and one for buy. 
Fixes: #268  
There was only one error for two different cases and error name itself was not accurate. Two different errors helps to better indicate what's the problem and when it actually occurs.
Run tests locally, fixed the broken one.
- [ v ] I have updated the documentation if necessary.
- [v ] This is a breaking change.
> fix(exchange): change pallet errors

- .github/workflows/tests.yml
Run tests with code coverage using tarpaulin. Upload to codecov.io
> ci: code coverage

- Cargo.lock
- pallets/xyk/src/lib.rs
- pallets/xyk/src/tests.rs
Add missing tests found by code coverage tools.
> test(xyk): add missing tests

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/constants.rs
- runtime/src/lib.rs
- runtime/src/tests.rs
Current fees for a TX are set too low. Tune the costs.
> feat!: update fee calculation

- scripts/list_crate_updates.sh
Fix: version check always reports that runtime versions don't match.
> ci: fix incorrect output from version check

- runtime/common/src/lib.rs
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/mock.rs
- runtime/hydradx/src/tests/mod.rs
- runtime/hydradx/src/tests/vested_transfer.rs
- runtime/testing-hydradx/src/lib.rs
- scripts/upgrade-runtime/index.js
- scripts/upgrade-runtime/package-lock.json
Related to https://github.com/galacticcouncil/HydraDX-node/issues/373 and https://github.com/galacticcouncil/Basilisk-crowdloan-ui/issues/30
* adds vesting account to whitelist for vested_transfer
* lowers MinVestedTransfer to allow for vestings under existential deposit
> feat: added vesting account and lowered minimal vested transfer

- scripts/snakenet-migration/index.js
Use weight split instead of call split because weight limits are different in parachain setup. 
Added check of max calls per batch too to not exceed max call per batch.
> fix: migration - use weight split

- README.md
- rococo-local/testing-config.json
We realized that the README about running the node with local testnet is outdated on our parachain branch. So I used the same setup as in Basilisk-node (master). Next to that, I also added a testing-config.json (to use testing runtime) as Lumir noted that that was also missing.
See description
I executed the commands described in the updated README to see if the node can be launched.
> Fix: update README about spinning up node with local testnet 

- pallets/omnipool/src/lib.rs
Remove imbalance update from `init_pool`. Imbalance is always zero at the point of omnipool initialization. 
therefore, it is not needed to recalculate and update it. 
Fixed #429
> fix: remove imbalance update from init_pool

- pallets/omnipool/src/tests/types.rs
- pallets/omnipool/src/types.rs
Fixed #432 
Sign should be consistent for 0 value. In case of sub - it could result in positive.
> fix: omnipool imbalance subtraction 

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/buy.rs
Fixed #439 
trade limit was compared against incorrect asset amount.
Test is adjusted so it fails with the "incorrect asset amount" but does not where the limit is compared against correct asset amount.
> fix: incorrect limit check when trading hub asset

- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/buy.rs
- pallets/omnipool/src/tests/mod.rs
- pallets/omnipool/src/tests/remove_liquidity.rs
- pallets/omnipool/src/tests/sell.rs
- pallets/omnipool/src/tests/verification/scenario_08.rs
- pallets/omnipool/src/tests/verification/scenario_10.rs
- pallets/omnipool/src/tests/verification/scenario_11.rs
Fixes #438 
Fixed #448 
The PR also fixes issue where too much hub asset is burned in remove_liquidity. It should burn only difference between delta_hub and amount which is transferred to LP.
Additional change ensures that a trade can only burn LRNA and returns error when it tries to mint ( to prevent potential bugs if such would occur to avoid erroneous minting).
> fix: correctly update hdx subpool hub reserve

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/types.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
Derive TypeInfo instead of implementing it manually as that did not work correctly.
> fix: omnipool asset trade state - derive typeinfo

- Cargo.lock
- integration-tests/Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
This PR removes nft pallet from runtime. 
Omnipool uses Uniques directly.
> chore: remove nft pallet from runtime

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/add_liquidity.rs
- pallets/omnipool/src/tests/remove_liquidity.rs
- pallets/omnipool/src/types.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
This PR changes storage of position price from FixedU128 to rational number. 
rather than storing calculted price ,we store the values to calculate price. This helps in future when price would be required to have higher precision and fixed128 would be replace by another fixed type.
> feat: change position price type to store as rational

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/non_native_fee.rs
- integration-tests/src/omnipool_init.rs
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/benchmarks.rs
- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/tests/invariants.rs
- pallets/omnipool/src/tests/mock.rs
- pallets/omnipool/src/tests/tvl.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
This PR removes TVL cap constant from pallet's config and introduces TVL cap as stored value.
This value can be changed using set_tvl_cap extrinsic.
> feat: make omnipool's tvl cap stored value

- .github/workflows/tests.yml
`test-upgrade-runtime` job fails because it's unable to locate an artifact. The job requires the binary uploaded from the `master` branch.
> ci: missing artifact

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/migration.rs
- pallets/omnipool/src/tests/imbalance.rs
- pallets/omnipool/src/tests/invariants.rs
- pallets/omnipool/src/tests/mod.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/migrations.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
based on https://github.com/galacticcouncil/HydraDX-math/pull/87
> feat: omnipool latest math - imbalance adjustment

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/tests/imbalance.rs
Adding a test to ensure that after certain amount of trades, imbalance is correctly reduced to 0 and subsequent operations work correctly.
> test: add test to ensure omnipool's imbalance is reduced to 0 correctly

- Cargo.lock
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool-liquidity-mining/src/lib.rs
This PR changes type in the calculation in `get_token_value_in_hub_asset()` to prevent multiplication overflow.
> fix: potential overflow in get_position_value_in_hub_asset

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/lib.rs
- pallets/omnipool/src/traits.rs
This PR adds origin to omnipool hooks. 
It also includes hook weight in the extrinsic weight
And also adds on_trade to buy ( missed before).
> feat: add origin and weight info  to omnipool hooks

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/circuit_breaker.rs
- pallets/circuit-breaker/Cargo.toml
- pallets/circuit-breaker/README.md
- pallets/circuit-breaker/src/lib.rs
- pallets/circuit-breaker/src/tests/omnipool.rs
- pallets/circuit-breaker/src/tests/trade_volume.rs
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/lib.rs
- runtime/common/Cargo.toml
- runtime/common/src/weights/circuit_breaker.rs
> fix: circuit breaker weights, events refactor

- Cargo.lock
- pallets/omnipool/Cargo.toml
- pallets/omnipool/src/lib.rs
This PR removes unused omnipool public functions. These removed functions would be only needed for subpool integration, however as discussed, trade will be routed through omnipool and stableswap directly. There is no need for them
> chore: remove unused omnipool api

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/cross_chain_transfer.rs
- runtime/common/Cargo.toml
- runtime/common/src/adapters.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/xcm.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
When receiving tokens via `TransactAsset` we check whether it is trying to go into an existing Omnipool account. If that's the case we reroute into the treasury.
Replaces the existing ORML `TransactAsset` implementation with a near-clone.
We want to disallow price manipulation via moving tokens into pool accounts.
See the included integration test.
> fix: reroute XCM tokens going to Omnipool Account

- Cargo.lock
- integration-tests/Cargo.toml
- pallets/circuit-breaker/Cargo.toml
- pallets/omnipool-liquidity-mining/Cargo.toml
- pallets/omnipool/Cargo.toml
- runtime/common/Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/benchmarking/mod.rs
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/migrations.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
Add a migration for the asset registry that removes `locked` and introduces `xcm_rate_limit`.
https://github.com/galacticcouncil/warehouse/pull/209
> feat: asset registry xcm rate limit

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/dca.rs
- pallets/dca/Cargo.toml
- pallets/dca/src/benchmarks.rs
- pallets/dca/src/lib.rs
- pallets/dca/src/tests/mod.rs
- pallets/dca/src/tests/on_initialize.rs
- pallets/dca/src/tests/schedule.rs
- pallets/dca/src/types.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/testing-hydradx/Cargo.toml
- runtime/testing-hydradx/src/lib.rs
> feat: dca slippages and retries configurable

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/dca.rs
- pallets/route-executor/Cargo.toml
- pallets/route-executor/src/lib.rs
> fix: router ED leftover balance check

- Cargo.lock
- math/Cargo.toml
- math/src/stableswap/tests/multi_assets.rs
- pallets/stableswap/Cargo.toml
- pallets/stableswap/src/lib.rs
- pallets/stableswap/src/tests/trades.rs
There is a little bug in sell functionality where the order are flipped as input to calculate_out_amount function. 
This works ok (ish) for pools where assets have all the same decimals but becomes more obvious where there is one with different number of decimals. Hence spotted quite late.
> fix: stableswap asset order

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/system.rs
- runtime/hydradx/src/xcm.rs
Allow polkadotXcm.send to be called locally as an extrinsic and remotely within a XCM Transact call
> feat: enable polkadotXcm.send

- Cargo.lock
- pallets/asset-registry/Cargo.toml
- pallets/asset-registry/src/lib.rs
- pallets/asset-registry/src/types.rs
- traits/Cargo.toml
- traits/src/registry.rs
This PR refactors registry trait for asset creation. Previously it was not possible to specify asset type as parameter, so there was not a way to create other assets than share PoolAsset type. 
With new types, Stableswap and Bond, it is required to register such type trhough some kind of generic interface.
Hence, the new CreateRegistry trait.
> feat: add generic create registry asset which accepts asset type

- Dockerfile
It related to ISSUE-665 https://github.com/galacticcouncil/HydraDX-node/issues/665
Another solution which should be better, but it also would cause the compiling phase running for hours. I guess it will introduce a side effect to your working process.
```
FROM rust:1.67 as builder
RUN \
--mount=type=cache,target=/var/cache/apt \
apt update && \
apt dist-upgrade -y && \
apt install -y protobuf-compiler clang
WORKDIR /usr/src/hydradx-node
COPY . .
RUN cargo build
FROM ubuntu:22.04
LABEL org.opencontainers.image.source = "https://github.com/galacticcouncil/HydraDX-node"
RUN useradd -m -u 1000 -U -s /bin/sh -d /hydra hydra && \
mkdir -p /hydra/.local/share && \
chown -R hydra:hydra /hydra
COPY --from=builder /usr/src/hydradx-node/target/release/hydradx /usr/local/bin/hydradx
RUN chmod +x …
```
> chore: update Docker image from Ubuntu 21.04 to Ubuntu 22.04

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/system.rs
Note: Call filter is called from Transact filter, so there is no need to update Transact filter
> feat: forbid XYK pools containing LRNA

- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec/mod.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/migrations.rs
Removes the chainId migration introduced in https://github.com/galacticcouncil/HydraDX-node/pull/646
Also, it sets a different chainId in the chain_spec
> chore: Cleanup EVM storage migration

- Cargo.lock
- math/Cargo.toml
- math/src/transcendental.rs
This PR fixes an issue found in exp function where e^(-1) is handled incorrectly. 
The impact is low as this case is unlikely to happen in LBP where the pow function is used.
> fix: incorrect handling of neg operand in exp function

- .github/workflows/tests.yml
Should fix the error from `version-check` job:
`Error: Resource not accessible by integration`
> ci: add write permission for version-check job

- node/res/hydradx.json
This PR adds the Helikon boot node (through `p2p` and `wss/p2p`) to the HydraDX chain specification at [/node/res/hydradx.json](https://github.com/galacticcouncil/HydraDX-node/blob/master/node/res/hydradx.json).
To test:
```
./hydradx --chain hydradx --tmp --reserved-only --reserved-nodes "/dns4/boot.helikon.io/tcp/15120/p2p/12D3KooWDcQY1L2ny3F7YPyP4snCZZYc4eKWgPLEzdBvWBUjH5Yt"
./hydradx --chain hydradx --tmp --reserved-only --reserved-nodes "/dns4/boot.helikon.io/tcp/15125/wss/p2p/12D3KooWDcQY1L2ny3F7YPyP4snCZZYc4eKWgPLEzdBvWBUjH5Yt"
```
> feat: add Helikon boot node for HydraDX

- Cargo.lock
- pallets/asset-registry/Cargo.toml
- pallets/asset-registry/src/migration.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
This PR prevents to run migration of asset-registry from v1 to v2 if pallet's version is not `1`.
> chore: prevent to run asset-registry's v2 migration second time

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/router.rs
Added a few more integration tests to cover edge cases as we figured out a way to cover them meaningfully.
> fix: add missing set route tests

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/evm.rs
- integration-tests/src/polkadot_test_net.rs
- pallets/transaction-multi-payment/Cargo.toml
- pallets/transaction-multi-payment/src/lib.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/lib.rs
The operation fails already when MM does a dry-run estimateGas(...) on the transaction.  When insufficient asset is bought, on_funds is triggered where we try to retrieve the price of the fee payment asset from the multi-pallet: https://github.com/galacticcouncil/HydraDX-node/blob/8abf856afa839b798c4e39e38af2b2901f55739b/runtime/hydradx/src/assets.rs#L174
But at the point of dry-run, the storage is empty, so it doesn't contain the accepted currency prices, as they are populated only  in on_initialize of multi pallet.
The solution is to calculate the oracle onchain price directly instead of getting the prices from an empty prices storage of MultiPaymentPallet
> fix: swaps of insufficient asset via evm

- Cargo.lock
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
This PR fixes the following error produced when the runtime is build:
`error: cannot find macro thread_local in this scope
--> precompiles/utils/src/evm/handle.rs:111:1
|
111 | environmental::environmental!(EVM_CONTEXT: trait PrecompileHandle);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: thread_local is in scope, but it is an attribute: #[thread_local]`
> fix: runtime build

- Cargo.lock
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/lib.rs
This PR lowers `MinTotalFarmRewards` for omnipool liquidity mining.
This is safe to lower as farms' creation needs to go through governance.
> chore: lower `minTotalFarmRewards` for omnipool liquidity mining

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- node/src/chain_spec/local.rs
- node/src/chain_spec/mod.rs
- node/src/chain_spec/rococo.rs
- node/src/chain_spec/staging.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/evm/mod.rs
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/xcm.rs
Fixes: #813. This PR removes deprecated method `from_genesis` and replaces it with `builder`.
> refactor: use genesis builder

- Cargo.lock
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/xcm.rs
> refactor: remove xcm stale code

- Cargo.lock
- node/Cargo.toml
- node/src/command.rs
- node/src/service.rs
Work done in https://github.com/galacticcouncil/hydration-node/pull/878, prepared for a release.
> fix: Stop using the native executor

- Cargo.lock
- pallets/otc-settlements/Cargo.toml
- pallets/otc-settlements/README.md
- pallets/otc-settlements/src/lib.rs
- pallets/otc-settlements/src/mock.rs
- pallets/otc-settlements/src/tests.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
After this fix, the pallet tries to minimize an arb if the exact amount to close the arb is not found.
> fix: otc settlements

- .github/workflows/tests.yml
Added new job ecosystem-tests, running some XCM regression tests
> test: runtime wasm regression tests

- Cargo.lock
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/lib.rs
This PR lowers `MinTotalFarmRewards` for xyk liquidity mining.
This is safe to lower as farms' creation needs to go through governance.
> chore: lower minTotalFarmRewards for xyk liquidity mining

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/router.rs
- pallets/stableswap/Cargo.toml
- pallets/stableswap/src/lib.rs
- pallets/stableswap/src/tests/remove_liquidity.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
We should not do this check as we can have accounts with balance less than `T::MinPoolLiquidity` then the following check prevents the shares withdrawal
https://github.com/galacticcouncil/hydration-node/blob/ea4e622fe5adb0dda12dd4000ac6b55849ff7649/pallets/stableswap/src/lib.rs#L574-L578
TODO:
> fix: remove stableswap ed check

- Cargo.lock
- math/Cargo.toml
- math/src/staking/math.rs
- math/src/staking/tests.rs
- pallets/staking/Cargo.toml
- pallets/staking/src/lib.rs
- pallets/staking/src/migrations.rs
- pallets/staking/src/tests/mock.rs
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/lib.rs
This PR add 6 sec. blocks support to pallet staking.
> feat: 6 sec. blocks support for pallet_staking

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/staking.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/lib.rs
This PR is lowering staking's min. slash to 5 points from 50.
> chore: lower staking min. slash

- Cargo.lock
- Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/governance/mod.rs
- runtime/hydradx/src/lib.rs
This extrinsic can be called by any TechnicalCommittee member in order to remove the votes of a user, and calculate the total lock. This is a prerequisite for async backing (https://github.com/galacticcouncil/hydration-node/pull/982)
For the changes in pallet-conviction-voting see https://github.com/galacticcouncil/polkadot-sdk/pull/10
> feat: add force_remove_vote to pallet-conviction-voting

- pallets/stableswap/src/benchmarks.rs
- pallets/stableswap/src/lib.rs
- pallets/stableswap/src/tests/add_liquidity.rs
- pallets/stableswap/src/trade_execution.rs
- pallets/stableswap/src/weights.rs
- runtime/hydradx/src/weights/pallet_stableswap.rs
This PR adds new extrinsic that adds liquidity `add_assets_liquidity`. 
The difference between add_liquidity and add_assets_liquidity is that this new extrisnics allows to specify min shares that LP expects to receive.
> feat: stableswap - add liquidity limit

- integration-tests/src/aave_router.rs
- integration-tests/src/dca.rs
- integration-tests/src/driver/mod.rs
- integration-tests/src/omnipool_liquidity_mining.rs
- integration-tests/src/router.rs
- pallets/stableswap/src/benchmarks.rs
- pallets/stableswap/src/lib.rs
- pallets/stableswap/src/tests/add_liquidity.rs
- pallets/stableswap/src/tests/amplification.rs
- pallets/stableswap/src/tests/creation.rs
- pallets/stableswap/src/tests/mock.rs
- pallets/stableswap/src/tests/mod.rs
- pallets/stableswap/src/tests/peg.rs
- pallets/stableswap/src/tests/peg_one.rs
- pallets/stableswap/src/tests/remove_liquidity.rs
- pallets/stableswap/src/tests/update_pool.rs
- pallets/stableswap/src/trade_execution.rs
- runtime-mock/src/stableswap.rs
This PR address minor findings in stableswap pallet.
1. Doc/comment update
2. Vec -> boundedvec
3. remove liquidity min amounts check
4. destroy pool removes peg info
5. added invariant check to withdraw_asset_amount to be consistent with others
> feat: stableswap audit minor findings 

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/referrals.rs
- runtime/adapters/Cargo.toml
- runtime/adapters/src/lib.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
TODO:
Within a router trade, we have the router account that executes the trade
It leads to incorrectly processed fee and reward accrue in [on_trade](https://github.com/galacticcouncil/hydration-node/blob/174ac5d13f0eca23b120b61ed57b854079d2f939/runtime/adapters/src/lib.rs#L486) event handler.
https://github.com/galacticcouncil/hydration-node/blob/174ac5d13f0eca23b120b61ed57b854079d2f939/runtime/adapters/src/lib.rs#L486
The fix is to use the actual user (instead of the router account) which we track in the broadcast pallet.
> fix: bug of referral fee processing within router

- Cargo.lock
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/evm/aave_trade_executor.rs
- runtime/hydradx/src/lib.rs
in aave sell amount calculation,we dont account for rounding currently.
This PR fixes that.
Some failing DCA: https://hydration.subscan.io/block/7396904?tab=event&event=7396904-31
> fix: DCA expecting exact amount of aTokens received

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/call_filter.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- runtime/hydradx/src/system.rs
This PR call filters out `nft::burn()` call. This stops burning of nfts outside of pallets that created it and stops creation of dead positions
> fix: prevent nft burning outside of pallet that created it

- .github/workflows/tests.yml
we need to use a source of truth, to make the tests easily updateable
> fix: use specific branch for regression tests

- .github/workflows/wasm-builder.yml
- Makefile
The built runtime had no metadata hash enabled, so we need to enable it with `build-ops` flags
```
Passing the metadata hash feature in the --build-opts fixes it, or at least we can send that signed transaction in the test.
This is how moonbean also pass their additional feature.
srtool -e docker build -p "hydradx-runtime" --app --image docker.io/paritytech/srtool --build-opts="--features=metadata-hash" --root
But not sure why --default-features doesnt work, I also tried with env variable, but no success.
```
> fix: metadata hash in srtool build

- precompiles/call-permit/Cargo.toml
- precompiles/flash-loan/Cargo.toml
- precompiles/utils/Cargo.toml
- precompiles/utils/tests-external/Cargo.toml
ThisPR reverts recent change that added forbid-evm-reentrancy features
Unfortunately, this breaks some features that requires to do calls to evm multiple times.
> fix: remove added pallet-evm features

- Cargo.lock
- pallets/liquidity-mining/Cargo.toml
- pallets/liquidity-mining/src/lib.rs
- pallets/liquidity-mining/src/tests/deposit_lp_shares.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
- traits/Cargo.toml
This PR remove `deposit.shares >= min_deposits` and leave only `valued_shares >= min_deposit` check
> fix: remove redundant min. deposit check

- Cargo.lock
- Cargo.toml
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/lib.rs
This PR bumps polkadot-sdk with patch5 which backports a fix for duplicate message codec indices which breaks the fuzzer.
Original issue: stable2409-patch4
Changelog: https://github.com/galacticcouncil/polkadot-sdk/compare/stable2409-patch4...galacticcouncil:polkadot-sdk:stable2409-patch5
> chore: Bump polkadot-sdk to stable2409-patch5

- Cargo.lock
- pallets/stableswap/Cargo.toml
- pallets/stableswap/src/benchmarks.rs
- pallets/stableswap/src/lib.rs
- pallets/stableswap/src/tests/mod.rs
- pallets/stableswap/src/tests/update_max_peg_update.rs
- pallets/stableswap/src/tests/update_peg_source.rs
- pallets/stableswap/src/weights.rs
- runtime/hydradx/src/weights/pallet_stableswap.rs
> feat: stableswap - support to update pool peg data

- launch-configs/fork/prepare-state-for-zombienet.js
This PR updates prepare chainspec script for zombienet fork to set omnipool and xyk LM `yieldFarm.updated_at` to 0 and xyk LM `globalFarm.udpated_at` to 0.
> chore: zombienet fork, set yieldFarm.updated_at to 0

- Cargo.lock
- integration-tests/Cargo.toml
- integration-tests/src/hsm.rs
- pallets/hsm/Cargo.toml
- pallets/hsm/src/lib.rs
- pallets/hsm/src/tests/arb.rs
- pallets/hsm/src/tests/mock.rs
- runtime/hydradx/Cargo.toml
- runtime/hydradx/src/assets.rs
- runtime/hydradx/src/lib.rs
this pr adds minor improvement to hsm:
1. Arbitrage profit now transferred to given ArbitrageProfitReceiver - set to Treasury 
2. HSm account and loan receiver account are whitelisted, so it is not dusted.
3. Added additional info to ArbitrageExecuted event.
> feat: hsm - account whitelisting, arb profit receiver
